default['solr']['dist_file_url'] = "/installers/solr.tar.gz"
default['solr']['folder_name'] = "/solr"
default['solr']['home_dir'] = "/opt/jv"
default['solr']['port'] = "9095"
default['solr']['ajp_port'] = "8025"
default['solr']['serverport'] = "8026"